version: '3.8'

services:
  # === 1. База Данных ===
  postgres_db:
    image: postgres:16
    container_name: kaizen_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: kaizendb
    ports:
      - "5432:5432"
    volumes:
      # Используем локальный том, чтобы не путать с VPS
      - postgres_data_local:/var/lib/postgresql/data
    restart: always

  # === 2. Хранилище MinIO ===
  minio:
    image: minio/minio
    container_name: kaizen_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_local:/data
    restart: always

  # === 3. Настройка MinIO (Создание бакетов) ===
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "

volumes:
  postgres_data_local:
  minio_data_local: