version: '3.8'

services:
  # 1. База Данных
  postgres_db:
    image: postgres:16
    container_name: kaizen_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: kaizendb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_vps:/var/lib/postgresql/data
    restart: always

  # 2. Твой API (Сервер)
  kaizen-api:
    build:
      context: ./KaizenEstate.API  # Путь к папке API
      dockerfile: Dockerfile
    container_name: kaizen_api_container
    depends_on:
      - postgres_db
      - minio
    ports:
      - "8080:8080" # Открываем порт 8080 наружу
    environment:
      # Важно: Host=postgres_db — это имя сервиса базы внутри докера
      ConnectionStrings__DefaultConnection: "Host=postgres_db;Port=5432;Database=kaizendb;Username=admin;Password=password123"
      # Настройки MinIO
      Minio__Endpoint: "minio:9000"
      Minio__AccessKey: "minioadmin"
      Minio__SecretKey: "minioadmin"
    restart: always

  # 3. Хранилище картинок MinIO
  minio:
    image: minio/minio
    container_name: kaizen_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data_vps:/data
    restart: always

  # 4. Настройка MinIO (создает папку images)
  createbuckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/images;
      /usr/bin/mc anonymous set public myminio/images;
      exit 0;
      "

volumes:
  postgres_data_vps:
  minio_data_vps: